name: Sync Fork

on:
  schedule:
    - cron: '0 4 * * *'   # ogni giorno alle 04:00 UTC (06:00 ora italiana)
  workflow_dispatch:        # abilita il pulsante "Run workflow" manuale

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream
        run: gh repo sync osensei78/flipperzero-firmware-wPlugins --source RogueMaster/flipperzero-firmware-wPlugins
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
